-- ============================================================
-- ALTER TABLE audit record
-- status    : EXECUTED
-- tabella   : AspNetUsers
-- token     : 84075504D4ED
-- timestamp : 2026-04-02 17:15:06 UTC
-- ============================================================

-- DISINNESCATA il 2026-08-09.
-- Lo statement è già stato eseguito il 2026-04-02; l'utente 'davraf' è stato
-- successivamente ricreato ed è oggi l'account Admin attivo.
-- Rieseguire l'intera cartella schema-migrations/ lo cancellerebbe di nuovo,
-- quindi lo statement resta a scopo di sola documentazione storica.
-- DELETE FROM AspNetUsers WHERE UserName = 'davraf';