// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dr.NutrizioNino.Api.Models.Configurations;
using Dr.NutrizioNino.Models.Dto;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace Dr.NutrizioNino.Api.Models;

public partial class DrNutrizioNinoContext : DbContext
{
    public DrNutrizioNinoContext(DbContextOptions<DrNutrizioNinoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Food> Foods { get; set; }

    public virtual DbSet<FoodNutrient> FoodsNutrients { get; set; }

    public virtual DbSet<Nutrient> Nutrients { get; set; }

    public virtual DbSet<UnitOfMeasure> UnitsOfMeasures { get; set; }

    public virtual DbSet<NutrientsGetForFoodCreatingInfo> NutrientsGetForFoodCreatingInfoes { get; set; }

    public virtual DbSet<FoodDashboardInfo> FoodsDashboard { get; set; }

    public virtual DbSet<NutrientInfo> NutrientInfoes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.BrandConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FoodConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FoodsNutrientConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.NutrientConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UnitsOfMeasureConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.NutrientsGetForFoodCreatingInfoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FoodDashboardConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
