// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dr.NutrizioNino.Api.Models;

public partial class FoodNutrient
{
    public Guid FoodId { get; set; }

    public Guid NutrientId { get; set; }

    public int UnitOfMeasure { get; set; }

    public decimal Quantity { get; set; }

    public virtual Food Food { get; set; }

    public virtual Nutrient Nutrient { get; set; }
}