// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dr.NutrizioNino.Api.Models;

public partial class Nutrient
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public int PositionOrder {  get; set; }
    public virtual ICollection<FoodNutrient> FoodsNutrients { get; set; } = new List<FoodNutrient>();
}