// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dr.NutrizioNino.Api.Models;

public partial class UnitOfMeasure
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Abbreviation { get; set; }    
    public virtual ICollection<Food> Foods { get; set; } = new List<Food>();
}