// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dr.NutrizioNino.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Dr.NutrizioNino.Api.Models.Configurations
{
    public partial class FoodsNutrientConfiguration : IEntityTypeConfiguration<FoodNutrient>
    {
        public void Configure(EntityTypeBuilder<FoodNutrient> entity)
        {
            entity.HasKey(e => new { e.FoodId, e.NutrientId }).HasName("PK_Nutrients");

            entity.ToTable("Foods_Nutrients");

            entity.Property(e => e.Quantity).HasColumnType("numeric(4, 2)");

            entity.HasOne(d => d.Food).WithMany(p => p.FoodsNutrients)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Foods_Nutrients_Foods");

            entity.HasOne(d => d.Nutrient).WithMany(p => p.FoodsNutrients)
                .HasForeignKey(d => d.NutrientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Foods_Nutrients_Nutrients");

            entity.HasOne(d => d.UnitOfMeasureNavigation).WithMany(p => p.FoodsNutrients)
                .HasForeignKey(d => d.UnitOfMeasureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Foods_Nutrients_UnitsOfMeasures");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FoodNutrient> entity);
    }
}
