// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dr.NutrizioNino.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Dr.NutrizioNino.Api.Models.Configurations
{
    public partial class FoodConfiguration : IEntityTypeConfiguration<Food>
    {
        public void Configure(EntityTypeBuilder<Food> entity)
        {
            entity.ToTable("Foods");
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Barcode).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Quantity).HasColumnType("numeric(6, 2)");

            entity.HasOne(d => d.Brand).WithMany(p => p.Foods)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK_Foods_Brands");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Food> entity);
    }
}
