// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dr.NutrizioNino.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Dr.NutrizioNino.Api.Models.Configurations
{
    public partial class FoodConfiguration : IEntityTypeConfiguration<Food>
    {
        public void Configure(EntityTypeBuilder<Food> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Barcode).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Quantity).HasColumnType("numeric(4, 2)");

            entity.HasOne(d => d.Brand).WithMany(p => p.Foods)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK_Foods_Brands");

            entity.HasOne(d => d.UnitOfMeasure).WithMany(p => p.Foods)
                .HasForeignKey(d => d.UnitOfMeasureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Foods_UnitsOfMeasure");

            entity.HasMany(d => d.Nutrients).WithMany(p => p.Foods)
                .UsingEntity<Dictionary<string, object>>(
                    "FoodsNutrient",
                    r => r.HasOne<Nutrient>().WithMany()
                        .HasForeignKey("NutrientsId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_Foods_Nutrients_Nutrients"),
                    l => l.HasOne<Food>().WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_Foods_Nutrients_Foods"),
                    j =>
                    {
                        j.HasKey("FoodId", "NutrientsId");
                        j.ToTable("Foods_Nutrients");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Food> entity);
    }
}
