// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dr.NutrizioNino.Api.Models;

public partial class Food
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public decimal Quantity { get; set; }

    public string Barcode { get; set; }

    public Guid? BrandId { get; set; }

    public decimal Calorie { get; set; }
    public Guid UnitOfMeasureId { get; set; }

    public virtual Brand Brand { get; set; }
    public virtual UnitOfMeasure UnitOfMeasure { get; set; }

    public virtual ICollection<FoodNutrient> FoodsNutrients { get; set; } = new List<FoodNutrient>();

}