@Dr.NutrizioNino.Api_HostAddress = http://localhost:5083
@FoodId = 00000000-0000-0000-0000-000000000000

GET {{Dr.NutrizioNino.Api_HostAddress}}/api/v1/foods/getnewfood
Accept: application/json

###

GET {{Dr.NutrizioNino.Api_HostAddress}}/api/v1/foods/{{FoodId}}
Accept: application/json

###

GET {{Dr.NutrizioNino.Api_HostAddress}}/api/v1/brands
Accept: application/json

###

GET {{Dr.NutrizioNino.Api_HostAddress}}/api/v1/nutrients
Accept: application/json

###

GET {{Dr.NutrizioNino.Api_HostAddress}}/api/v1/unitsOfMeasures
Accept: application/json

###
